from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BRAIN_DIR = ROOT / "brain"

OFFICIAL = "official_guidelines_2026_hs"
GUIDE = "guide_2026_hs"
CHANGES = "changes_ppt_2026_hs"
TRAINING = "training_ppt_2026_hs"


def ref(doc_id: str, printed_page: int | str | None = None, slide: int | str | None = None) -> dict:
    data = {"docId": doc_id}
    if printed_page is not None:
        data["printedPage"] = printed_page
    if slide is not None:
        data["slide"] = slide
    return data


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(json.dumps(record, ensure_ascii=False) for record in records)
    path.write_text(body + ("\n" if body else ""), encoding="utf-8")


def build_change_cards() -> list[dict]:
    return [
        {
            "changeId": "chg_2026_001_accumulation_authority",
            "topicId": "creative_experience",
            "title": "누가기록 여부 및 방법 결정 주체가 시도교육감에서 학교장으로 변경",
            "before2025": "창의적 체험활동상황, 행동특성 및 종합의견 등의 누가기록 여부와 방법은 시도교육감이 정하는 구조로 안내되었다.",
            "after2026": "창의적 체험활동상황, 일상생활 활동상황, 행동특성 및 종합의견의 누가기록 여부 및 방법은 학교장이 정한다.",
            "practicalMeaning": "누가기록을 할지와 어떤 방식으로 운영할지는 학교별로 달라질 수 있으므로, 전국 공통 기준처럼 단정하지 말고 학교 방침을 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 28),
                ref(GUIDE, 10),
                ref(CHANGES, slide=3),
                ref(CHANGES, slide=4),
            ],
            "keywords": ["누가기록", "학교장", "시도교육감", "창의적 체험활동상황", "일상생활 활동상황", "행동특성 및 종합의견"],
        },
        {
            "changeId": "chg_2026_002_retention_definition",
            "topicId": "personal_school_status",
            "title": "유급 정의에서 졸업 요건 미충족을 분리하고 졸업유예로 별도 정리",
            "before2025": "유급 정의에 해당 학년 미수료뿐 아니라 졸업에 필요한 학점을 취득하지 못한 경우까지 함께 포괄하는 표현이 있었다.",
            "after2026": "유급은 해당 학년 교육과정 미수료로 상급 학년으로 진급하지 못하는 경우로 정리되고, 졸업 요건 미충족은 졸업유예로 분리되었다.",
            "practicalMeaning": "유급과 졸업유예를 같은 말처럼 답하면 안 된다. 진급 문제인지, 졸업 자격 문제인지를 구분해서 설명해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 34),
                ref(GUIDE, "11~12"),
                ref(CHANGES, slide=5),
            ],
            "keywords": ["유급", "졸업유예", "진급", "졸업 요건", "학점"],
        },
        {
            "changeId": "chg_2026_003_graduation_deferral",
            "topicId": "personal_school_status",
            "title": "졸업에 필요한 학점을 취득하지 못한 경우를 졸업유예로 별도 신설",
            "before2025": "출석일수는 충족했지만 졸업에 필요한 학점을 모두 취득하지 못한 상태를 설명하는 용어가 분명하게 정리되어 있지 않았다.",
            "after2026": "출석일수는 충족했으나 졸업에 필요한 학점을 모두 취득하지 못해 졸업 자격을 얻지 못한 경우를 졸업유예로 별도 정리했다.",
            "practicalMeaning": "출석 문제와 학점 문제를 따로 봐야 하며, 졸업 가능 여부를 안내할 때는 졸업유예 개념을 함께 설명해야 한다.",
            "gradeScope": "graduation_stage",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 35),
                ref(GUIDE, "12~13"),
                ref(CHANGES, slide=6),
                ref(CHANGES, slide=7),
            ],
            "keywords": ["졸업유예", "학점", "졸업 자격", "출석일수"],
        },
        {
            "changeId": "chg_2026_004_subject_attendance_rate",
            "topicId": "attendance",
            "title": "2026학년도 1·2학년 모두 과목출석률 관리가 핵심 기준으로 적용",
            "before2025": "2025학년도에는 고교학점제 적용 첫해인 1학년을 중심으로 학점 취득을 위한 과목출석률 관리가 본격 적용되기 시작했다.",
            "after2026": "2026학년도에는 1·2학년 모두 1학점당 수업량 16회의 3분의 2 이상 출석 기준을 적용하며, 과목 담당교사가 매시간 수업 참여 여부를 확인해 나이스에 입력하고 출석인정 결석 또는 결과는 출석으로 반영한다.",
            "practicalMeaning": "과목출석률 질문은 1·2학년 기준으로 먼저 답하고, 3학년과 혼동하지 않도록 학년 분기를 강하게 걸어야 한다.",
            "gradeScope": "grades_1_2",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 55),
                ref(GUIDE, "18~19"),
                ref(CHANGES, slide=8),
            ],
            "keywords": ["과목출석률", "1학점당 16회", "출석인정 결석", "출석인정 결과", "고교학점제", "1·2학년"],
        },
        {
            "changeId": "chg_2026_005_attendance_notes",
            "topicId": "attendance",
            "title": "출결 특기사항 입력 기준이 장기결석, 기타결석, 지각·조퇴·결과 중심으로 세분화",
            "before2025": "출결 특기사항 입력 기준은 있었지만 장기결석 범위, 기타결석 1일 기재, 잦은 지각·조퇴·결과의 입력 기준이 지금보다 덜 구조화되어 있었다.",
            "after2026": "장기결석은 결석 종류별 사유를 입력하고, 기타결석은 1일이라도 입력하며, 지각·조퇴·결과는 원칙적으로 입력하지 않되 반복적이거나 잦은 경우 사유를 입력할 수 있도록 정리했다.",
            "practicalMeaning": "출결 특기사항은 결석 종류와 빈도에 따라 답이 달라지므로, 단순히 입력한다 또는 입력하지 않는다고 묶어서 답하면 오류가 생긴다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 58),
                ref(GUIDE, 21),
                ref(CHANGES, slide=9),
                ref(CHANGES, slide=10),
            ],
            "keywords": ["출결 특기사항", "장기결석", "기타결석", "지각", "조퇴", "결과"],
        },
        {
            "changeId": "chg_2026_006_perfect_attendance",
            "topicId": "attendance",
            "title": "개근 입력 예외가 전입·재입학·특수교육 대상자까지 구체화",
            "before2025": "결석, 지각, 조퇴, 결과가 없으면 개근으로 입력하는 일반 원칙이 중심이었다.",
            "after2026": "중도 입학·전입·재입학의 출결 합산 방식과 순회교육학생, 건강장애학생, 원격수업 대상 특수교육대상자의 개근 공란 처리 예외를 구체적으로 정리했다.",
            "practicalMeaning": "개근 여부는 출결 숫자만으로 자동 판단하지 말고, 학적 변동과 특수 상황 예외를 함께 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 59),
                ref(GUIDE, 22),
                ref(CHANGES, slide=11),
            ],
            "keywords": ["개근", "전입", "재입학", "순회교육학생", "건강장애학생", "특수교육대상자"],
        },
        {
            "changeId": "chg_2026_007_award_plan",
            "topicId": "awards",
            "title": "교내상 입력 기준을 학년 초 학교교육계획과 2학기 초 변경계획 공개 중심으로 정리",
            "before2025": "학년 초 학교교육계획서에 따라 실시한 교내상만 입력할 수 있다는 구조로 안내되었다.",
            "after2026": "학년 초 학교교육계획에 연간 대회 및 수상내용 등의 실시계획을 기재하고, 그 계획에 따라 실시한 교내상만 수상경력에 입력한다. 다만 불가피한 경우 2학기 초 30일 이내 변경계획을 학교장 결재 후 공개한 경우에만 그 계획에 따른 교내상을 입력할 수 있다.",
            "practicalMeaning": "수상경력은 실제 수상 여부만 보면 안 되고, 연초 학교교육계획 반영 여부와 2학기 초 변경계획 공개 이행 여부를 함께 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "61~65"),
                ref(GUIDE, 24),
                ref(CHANGES, slide=12),
            ],
            "keywords": ["학교교육계획", "교내상", "수상경력", "2학기 초 30일", "학교장 결재", "변경계획 공개"],
        },
        {
            "changeId": "chg_2026_008_certificate_scope",
            "topicId": "certificates",
            "title": "자격증 입력 가능 범위를 국가기술·법령상 국가자격·교육부장관 지정 민간자격으로 명료화",
            "before2025": "국가공인 민간자격증 입력 가능 조건이 기술 관련 여부 중심으로 읽힐 여지가 있었다.",
            "after2026": "입력 가능한 자격은 국가기술자격, 법령에 따른 국가자격, 교육부장관이 지정한 국가공인 민간자격으로 명확히 정리하고, 민간자격은 공인 유효기간과 급수까지 확인하도록 했다.",
            "practicalMeaning": "민간자격이라는 이유만으로 곧바로 입력 여부를 판단하면 안 되고, 교육부장관 지정 여부와 공인 상태를 먼저 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "66~68"),
                ref(GUIDE, 25),
                ref(CHANGES, slide=13),
                ref(CHANGES, slide=14),
            ],
            "keywords": ["자격증", "국가기술자격", "국가자격", "국가공인 민간자격", "교육부장관", "유효기간"],
        },
        {
            "changeId": "chg_2026_009_generative_ai_caution",
            "topicId": "processing",
            "title": "생성형 AI 관련 유의사항이 학교생활기록부 신뢰도 항목에 명시",
            "before2025": "서술형 항목은 교사의 고유 권한이라는 원칙은 있었지만 생성형 AI 활용에 대한 금지와 검토 책임이 지금처럼 명시적이지 않았다.",
            "after2026": "학생이 대신 작성한 문장 제출 금지와 함께, 생성형 AI가 만든 문장을 검토 없이 그대로 입력하는 행위를 금지하고 교사가 최종 사실관계를 직접 확인해야 한다는 점을 분명히 했다.",
            "practicalMeaning": "AI를 썼는지보다 더 중요한 기준은 교사 직접 확인 여부다. AI가 만든 표현을 그대로 답변 근거처럼 쓰면 안 된다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 19),
                ref(CHANGES, slide=2),
                ref(TRAINING, slide=23),
            ],
            "keywords": ["생성형 AI", "서술형 항목", "교사 고유 권한", "직접 확인", "허위 기재"],
        },
        {
            "changeId": "chg_2026_010_storage_media_definition",
            "topicId": "processing",
            "title": "전산매체 정의가 현재 저장매체 표현으로 정비",
            "before2025": "전산매체를 자기테이프, 자기디스크 등 과거 중심 표현으로 설명하는 흐름이 남아 있었다.",
            "after2026": "전산매체를 CD, DVD, USB, 외장하드디스크 등 현재 학교 현장에서 사용하는 저장매체 중심으로 정리했다.",
            "practicalMeaning": "자료 보존이나 제출 방식을 설명할 때 오래된 예시를 그대로 반복하지 말고 현행 정의를 기준으로 답해야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 26),
                ref(GUIDE, 9),
            ],
            "keywords": ["전산매체", "USB", "외장하드디스크", "CD", "DVD"],
        },
        {
            "changeId": "chg_2026_011_english_examples_ai",
            "topicId": "processing",
            "title": "영문 입력 가능 예시에 AI가 추가",
            "before2025": "일반화된 영문 약어 예시는 있었지만 AI는 대표 예시로 제시되지 않았다.",
            "after2026": "부득이한 경우 영문으로 입력할 수 있는 일반화된 명사 예시에 AI를 포함했다.",
            "practicalMeaning": "AI라는 표기 자체는 허용 예시에 들어가지만, 이것이 AI 생성 문장의 입력 허용을 뜻하는 것은 아니라는 점을 함께 설명해야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 28),
                ref(GUIDE, 10),
                ref(TRAINING, slide=29),
            ],
            "keywords": ["영문 입력", "AI", "일반화된 명사", "처리요령"],
        },
        {
            "changeId": "chg_2026_012_creative_area_split",
            "topicId": "creative_experience",
            "title": "창의적 체험활동 영역명이 1·2학년과 3학년으로 분기",
            "before2025": "기존 고등학교 창의적 체험활동은 자율활동, 동아리활동, 봉사활동, 진로활동의 4개 영역 체계로 이해하는 것이 일반적이었다.",
            "after2026": "2026학년도에는 1·2학년은 자율·자치활동, 동아리활동, 진로활동의 3개 영역을 사용하고, 3학년은 기존 4개 영역 체계를 유지한다.",
            "practicalMeaning": "창체 질문은 반드시 학년을 먼저 나눠야 한다. 1·2학년과 3학년의 영역명 자체가 다르다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 77),
                ref(GUIDE, "26~29"),
            ],
            "keywords": ["창체", "1·2학년", "3학년", "자율·자치활동", "봉사활동", "진로활동"],
        },
        {
            "changeId": "chg_2026_013_school_sports_hours_removed",
            "topicId": "creative_experience",
            "title": "학교스포츠클럽 활동시간 기재가 삭제되고 동아리명 중심으로 정리",
            "before2025": "정규교육과정 이외 학교스포츠클럽 활동에서 활동시간을 함께 기재하는 방식이 가능하다고 이해되기 쉬웠다.",
            "after2026": "정규교육과정 이외 학교스포츠클럽 활동은 동아리활동 영역에 클럽명만 입력하고, 활동시간은 기재하지 않는다.",
            "practicalMeaning": "학교스포츠클럽 관련 질문에 시간을 적는지부터 답하면 틀리기 쉽다. 먼저 정규교육과정 이내인지 밖인지 구분해야 한다.",
            "gradeScope": "grades_1_2",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "84~85"),
                ref(CHANGES, slide=16),
            ],
            "keywords": ["학교스포츠클럽", "활동시간", "동아리명", "정규교육과정 이외"],
        },
        {
            "changeId": "chg_2026_014_school_sports_special_note_removed",
            "topicId": "creative_experience",
            "title": "정규교육과정 이외 학교스포츠클럽 특기사항은 입력하지 않도록 정리",
            "before2025": "정규교육과정 이외 학교스포츠클럽 활동에 대한 특기사항 기재 가능성이 남아 있었다.",
            "after2026": "정규교육과정 이외 학교스포츠클럽 활동은 동아리명만 입력하며 특기사항은 입력하지 않는다.",
            "practicalMeaning": "학교스포츠클럽 질문에는 시간과 특기사항을 따로 나눠 답해야 하며, 정규교육과정 이외 활동의 특기사항은 불가하다고 분명히 말해야 한다.",
            "gradeScope": "grades_1_2",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "84~85"),
                ref(CHANGES, slide=17),
            ],
            "keywords": ["학교스포츠클럽", "특기사항", "정규교육과정 이외", "동아리활동"],
        },
        {
            "changeId": "chg_2026_015_volunteer_content_limit",
            "topicId": "volunteer_service",
            "title": "봉사활동 실적의 활동내용 글자 수가 250자에서 50자로 축소",
            "before2025": "봉사활동 실적의 활동내용은 250자까지 입력할 수 있었다.",
            "after2026": "봉사활동 실적의 활동내용은 객관적이고 간략하게 50자 이내로 입력한다.",
            "practicalMeaning": "봉사활동 내용은 서술형 평가문처럼 길게 쓰면 안 된다. 사실 위주로 짧게 정리해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 208),
                ref(CHANGES, slide=52),
            ],
            "keywords": ["봉사활동", "활동내용", "50자", "250자"],
        },
        {
            "changeId": "chg_2026_016_career_note_limit",
            "topicId": "creative_experience",
            "title": "진로활동 특기사항 글자 수가 700자에서 500자로 조정",
            "before2025": "진로활동 특기사항은 700자까지 입력할 수 있었다.",
            "after2026": "진로활동 특기사항은 500자 이내로 입력한다.",
            "practicalMeaning": "진로활동 답변은 예전 분량 감각으로 길게 쓰지 말고, 현재 글자 수 제한을 전제로 간결성을 함께 안내해야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 208),
                ref(CHANGES, slide=52),
            ],
            "keywords": ["진로활동", "특기사항", "500자", "700자"],
        },
        {
            "changeId": "chg_2026_017_behavior_limit",
            "topicId": "behavior",
            "title": "행동특성 및 종합의견 글자 수가 500자에서 300자로 조정",
            "before2025": "행동특성 및 종합의견은 500자까지 입력할 수 있었다.",
            "after2026": "행동특성 및 종합의견은 300자 이내로 입력한다.",
            "practicalMeaning": "행특은 분량보다 핵심 사례 선별이 더 중요해졌다. 교육적 관점의 핵심 근거를 짧게 정리해야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 208),
                ref(CHANGES, slide=52),
            ],
            "keywords": ["행특", "행동특성 및 종합의견", "300자", "500자"],
        },
        {
            "changeId": "chg_2026_018_subject_progress_split",
            "topicId": "subject_progress",
            "title": "교과학습발달상황 체계가 1·2학년과 3학년으로 분리",
            "before2025": "교과학습발달상황을 한 체계로 이해해도 큰 혼동이 없던 시기였다.",
            "after2026": "2026학년도에는 1·2학년은 2022 개정 교육과정과 고교학점제 체계, 3학년은 기존 교육과정 체계로 나눠 봐야 한다.",
            "practicalMeaning": "세특, 성적, 이수 처리, 순위 규정 질문은 학년 분기를 먼저 거는 답변 구조가 필수다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "93~155"),
                ref(GUIDE, "52~67"),
            ],
            "keywords": ["교과학습발달상황", "1·2학년", "3학년", "세특", "성적"],
        },
        {
            "changeId": "chg_2026_019_grades_1_2_credit_system",
            "topicId": "subject_progress_grades_1_2",
            "title": "1·2학년은 학점, 5등급, 성취도별 분포비율 체계로 정리",
            "before2025": "기존 고등학교 성적 체계는 단위수와 9등급 중심으로 이해하는 흐름이 강했다.",
            "after2026": "1·2학년은 학점, 5등급, 성취도와 성취도별 분포비율을 중심으로 교과학습발달상황을 기록한다.",
            "practicalMeaning": "1·2학년 질문에 단위수나 9등급 기준을 끌어오면 오류가 난다. 학점과 5등급 체계로 답해야 한다.",
            "gradeScope": "grades_1_2",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 93),
                ref(GUIDE, "52~53"),
            ],
            "keywords": ["1·2학년", "학점", "5등급", "성취도", "성취도별 분포비율"],
        },
        {
            "changeId": "chg_2026_020_grade_3_unit_system",
            "topicId": "subject_progress_grade_3",
            "title": "3학년은 단위수와 9등급 체계를 유지",
            "before2025": "고등학교 교과학습발달상황은 전반적으로 단위수와 9등급 체계가 기본이었다.",
            "after2026": "3학년은 기존 교육과정에 따라 단위수와 9등급 체계를 계속 적용한다.",
            "practicalMeaning": "3학년 질문에 학점이나 5등급 기준을 섞지 않도록 주의해야 한다.",
            "gradeScope": "grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 124),
                ref(GUIDE, "52~53"),
            ],
            "keywords": ["3학년", "단위수", "9등급", "기존 교육과정"],
        },
        {
            "changeId": "chg_2026_021_completion_retake_markers",
            "topicId": "subject_progress",
            "title": "미이수·대체이수·재이수 처리 기준과 표기 범위가 정리",
            "before2025": "미이수, 대체이수, 재이수 상태를 어디에 어떤 말로 남길지에 대한 안내가 지금보다 덜 구조화되어 있었다.",
            "after2026": "미이수, 대체이수, 재이수 상태를 비고란과 이수 처리 기준 안에서 분명히 구분해 기록하도록 정리했다.",
            "practicalMeaning": "이수 처리 질문은 단순 성적 문제가 아니라 비고 표기와 학년 체계가 함께 엮인 문제로 봐야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, 94),
                ref(GUIDE, "57~63"),
                ref(CHANGES, slide=39),
                ref(CHANGES, slide=40),
                ref(CHANGES, slide=41),
            ],
            "keywords": ["미이수", "대체이수", "재이수", "비고란", "이수 처리"],
        },
        {
            "changeId": "chg_2026_022_online_content_remark",
            "topicId": "subject_progress",
            "title": "비고란 표기 예시에 온라인 콘텐츠가 추가",
            "before2025": "온라인 콘텐츠 이수 사실을 비고란에서 어떻게 표시할지 명시적 예시가 부족했다.",
            "after2026": "온라인 콘텐츠로 이수한 경우 비고란에 온라인 콘텐츠라고 입력하도록 정리했다.",
            "practicalMeaning": "온라인 이수 여부는 세특 본문에 길게 쓰기보다 비고란 표기 원칙부터 확인해야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, "94, 97"),
                ref(GUIDE, "60~61"),
                ref(CHANGES, slide=43),
            ],
            "keywords": ["온라인 콘텐츠", "비고란", "공동교육과정", "학교 밖 교육"],
        },
        {
            "changeId": "chg_2026_023_regular_exam_term",
            "topicId": "subject_progress",
            "title": "지필평가 용어를 정기시험으로 정비",
            "before2025": "교과학습발달상황과 평가 관련 설명에서 지필평가라는 용어를 사용했다.",
            "after2026": "정기시험과 수행평가라는 용어 체계로 정리했다.",
            "practicalMeaning": "현행 답변에서는 지필평가보다 정기시험을 기본 용어로 써야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 97),
                ref(TRAINING, slide=7),
                ref(CHANGES, slide=47),
            ],
            "keywords": ["정기시험", "지필평가", "수행평가", "용어 변경"],
        },
        {
            "changeId": "chg_2026_024_performance_assessment_ban",
            "topicId": "subject_progress",
            "title": "과제형·암기식 수행평가 금지 취지가 더 분명하게 안내",
            "before2025": "수행평가의 기본 원칙은 있었지만 과제형·암기식 수행평가를 피해야 한다는 현장 설명이 상대적으로 약했다.",
            "after2026": "정기시험과 수행평가 운영 안내에서 과제형 또는 단순 암기식 수행평가를 지양하고, 수업과 평가의 직접 연계를 강화하는 취지를 분명히 했다.",
            "practicalMeaning": "수행평가는 제출물 양보다 수업 중 관찰과 과정 중심 평가가 중요하다고 답해야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, "101, 132"),
                ref(TRAINING, slide=7),
            ],
            "keywords": ["수행평가", "과제형", "암기식", "직접 관찰", "과정 중심"],
        },
        {
            "changeId": "chg_2026_025_performance_assessment_ai",
            "topicId": "subject_progress",
            "title": "수행평가에서 생성형 AI 활용 유의사항을 별도로 강조",
            "before2025": "생성형 AI 활용이 수행평가의 공정성과 신뢰도에 미치는 영향에 대한 안내가 지금처럼 구체적이지 않았다.",
            "after2026": "수행평가에서 생성형 AI 활용 가능 범위와 금지 범위를 사전에 안내하고, 교사의 직접 관찰과 공정성 확보를 전제로 운영하도록 강조했다.",
            "practicalMeaning": "AI 사용 자체를 한마디로 허용 또는 금지라고 답하기보다, 사전 안내, 금지 범위 설정, 직접 관찰 원칙을 함께 설명해야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "101, 132"),
                ref(TRAINING, slide=7),
                ref(TRAINING, slide=132),
            ],
            "keywords": ["수행평가", "생성형 AI", "공정성", "직접 관찰", "사전 안내"],
        },
        {
            "changeId": "chg_2026_026_all_students_subject_notes",
            "topicId": "subject_progress",
            "title": "세특은 모든 학생 입력이 원칙이고 부득이한 경우에만 특이사항 없음 사용",
            "before2025": "과목별 세부능력 및 특기사항을 모든 학생에게 입력해야 한다는 원칙과 예외 문구 사용 조건이 지금보다 덜 분명했다.",
            "after2026": "교과학습발달상황의 서술형 항목은 모든 학생 입력이 원칙이며, 부득이한 경우에만 학업성적관리위원회 심의를 거쳐 특이사항 없음으로 입력할 수 있도록 정리했다.",
            "practicalMeaning": "세특이 비어 있는 것이 허용되는지 묻는 질문에는 원칙과 예외 절차를 함께 답해야 한다.",
            "gradeScope": "grades_1_2_vs_grade_3",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "95, 126"),
                ref(GUIDE, 63),
                ref(CHANGES, slide=44),
            ],
            "keywords": ["세특", "모든 학생 입력", "특이사항 없음.", "학업성적관리위원회"],
        },
        {
            "changeId": "chg_2026_027_reading_duplication",
            "topicId": "reading",
            "title": "독서활동상황에서 동일 도서도 증빙이 다르면 중복 입력 가능하도록 정리",
            "before2025": "동일 도서는 중복 입력하지 않는 방향으로 이해하는 경우가 많았다.",
            "after2026": "같은 도서라도 과목, 학년, 학기, 영역이 다르거나 증빙자료가 다르면 각각 입력할 수 있고, 원서와 번역본도 증빙이 다르면 각각 입력할 수 있도록 정리했다.",
            "practicalMeaning": "같은 책이라는 이유만으로 바로 불가라고 답하지 말고, 증빙자료와 기록 맥락이 다른지 먼저 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "156~157"),
                ref(GUIDE, 68),
                ref(CHANGES, slide=49),
            ],
            "keywords": ["독서활동상황", "동일 도서", "중복 입력", "증빙자료", "원서", "번역본"],
        },
        {
            "changeId": "chg_2026_028_preservation_reorganization",
            "topicId": "corrections",
            "title": "자료 보존 방식이 학교 보관 8년 후 전자보존 체계로 정리",
            "before2025": "학교생활기록부 보존 방식은 종이 출력과 전자보존 설명이 함께 섞여 이해되기 쉬웠다.",
            "after2026": "학교생활기록부 I·II는 전자적으로 준영구 보존하고, 학교에서는 졸업 후 8년간 보관한 뒤 전자적으로 보존하는 구조를 분명히 했다.",
            "practicalMeaning": "자료 보존 질문에는 종이 보관이 기본이라고 답하면 안 되고, 전자보존이 원칙이라는 점을 먼저 설명해야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 163),
                ref(GUIDE, "70~71"),
            ],
            "keywords": ["자료 보존", "전자보존", "준영구", "졸업 후 8년"],
        },
        {
            "changeId": "chg_2026_029_correction_evidence",
            "topicId": "corrections",
            "title": "자료 정정은 같은 학년도 객관적 증빙과 입력 주체 기준을 갖춰야 하도록 강화",
            "before2025": "마감 후 정정 시 객관적 증빙 필요성은 있었지만, 어떤 자료가 적정한 증빙인지 기준이 지금보다 덜 분명했다.",
            "after2026": "마감 후 정정은 해당 학년도에 생산된 객관적 증빙자료와 적정한 입력 주체가 만든 자료를 바탕으로 해야 하며, 서술형 항목이 서로 바뀌거나 누락된 경우는 학업성적관리위원회 심의를 거쳐 정정하도록 정리했다.",
            "practicalMeaning": "정정 질문에는 단순히 증빙자료가 있느냐만 묻지 말고, 언제 만들어진 자료인지와 누가 작성한 자료인지까지 확인해야 한다.",
            "gradeScope": "all_grades",
            "importance": "high",
            "sourceRefs": [
                ref(OFFICIAL, "165~166"),
                ref(GUIDE, "71~72"),
            ],
            "keywords": ["정정", "증빙자료", "같은 학년도", "입력 주체", "학업성적관리위원회"],
        },
        {
            "changeId": "chg_2026_030_commercial_use_restriction",
            "topicId": "processing",
            "title": "학교생활기록부의 상업적 이용 제한이 명시",
            "before2025": "학교생활기록부 활용 제한은 있었지만 상업적 이용 금지를 별도 조항으로 읽기 어려웠다.",
            "after2026": "학교생활기록부와 관련 자료의 상업적 이용 제한을 별도 조항으로 명시했다.",
            "practicalMeaning": "민간 서비스, 홍보, 영리 목적 재활용 여부를 묻는 질문에는 상업적 이용 제한 조항을 바로 근거로 제시할 수 있어야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 174),
                ref(GUIDE, 72),
            ],
            "keywords": ["상업적 이용", "활용 제한", "학교생활기록부"],
        },
        {
            "changeId": "chg_2026_031_evaluation_management_center",
            "topicId": "processing",
            "title": "평가관리센터 설치·운영 조항이 신설",
            "before2025": "학교생활기록부 기재요령에서 평가관리센터 설치·운영을 직접 다루는 조항은 없었다.",
            "after2026": "평가관리센터 설치·운영 관련 조항이 신설되어 관리 체계를 보완했다.",
            "practicalMeaning": "평가와 기록 관리 체계를 설명할 때 단순 실무 절차뿐 아니라 제도적 관리 장치가 추가되었다는 점도 함께 안내할 수 있어야 한다.",
            "gradeScope": "all_grades",
            "importance": "medium",
            "sourceRefs": [
                ref(OFFICIAL, 174),
                ref(GUIDE, 72),
            ],
            "keywords": ["평가관리센터", "설치", "운영", "관리 체계"],
        },
    ]


def build_rule_cards() -> list[dict]:
    return [
        {
            "ruleId": "rule_teacher_owns_descriptive_items",
            "topicId": "processing",
            "ruleSummary": "서술형 항목은 교사가 직접 작성하고 최종 책임도 교사에게 있다.",
            "allowed": ["교사가 평소 직접 관찰·평가한 내용을 바탕으로 서술형 항목을 작성한다."],
            "notAllowed": ["학생이 써서 제출한 문장을 거의 그대로 입력한다.", "AI가 만든 문장을 검토 없이 그대로 붙여 넣는다."],
            "conditions": ["생성형 AI를 참고했더라도 최종 문장과 사실관계는 교사가 직접 확인해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 19), ref(OFFICIAL, 27), ref(CHANGES, slide=2)],
            "keywords": ["서술형 항목", "교사 고유 권한", "학생 작성 금지", "AI"],
        },
        {
            "ruleId": "rule_no_direct_ai_generated_text",
            "topicId": "processing",
            "ruleSummary": "생성형 AI가 만든 문장을 검토 없이 그대로 입력하면 안 된다.",
            "allowed": ["교사가 표현을 다듬기 위한 참고 자료로만 AI를 활용할 수 있다."],
            "notAllowed": ["AI가 생성한 문장을 사실 확인 없이 그대로 입력한다.", "AI 산출물을 학생의 실제 수행처럼 서술한다."],
            "conditions": ["허위 또는 과장 기재 여부를 교사가 직접 검토해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 19), ref(TRAINING, slide=23)],
            "keywords": ["생성형 AI", "허위 기재", "사실 확인", "교사 검토"],
        },
        {
            "ruleId": "rule_input_based_on_direct_observation",
            "topicId": "processing",
            "ruleSummary": "기재 내용은 입력 주체의 직접 관찰과 평가에 근거해야 한다.",
            "allowed": ["교과 담당교사나 담임교사가 직접 확인한 학생 특성을 입력한다."],
            "notAllowed": ["간접 전언이나 확인되지 않은 자료만으로 서술형 항목을 작성한다."],
            "conditions": ["입력 주체가 누구인지와 어떤 교육활동에서 관찰했는지가 분명해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 27)],
            "keywords": ["입력 주체", "직접 관찰", "직접 평가"],
        },
        {
            "ruleId": "rule_hangul_default_english_only",
            "topicId": "processing",
            "ruleSummary": "학교생활기록부 문자는 한글이 원칙이고 부득이한 경우에만 영문을 쓴다.",
            "allowed": ["외국인 성명, 도로명 주소의 영문, 일반화된 영문 약어 등은 부득이한 경우 입력할 수 있다."],
            "notAllowed": ["한자나 다른 외국어 표기를 일반적으로 입력한다."],
            "conditions": ["누구나 이해하기 쉬운 표현인지 먼저 확인해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 28), ref(GUIDE, 92)],
            "keywords": ["한글 원칙", "영문", "한자", "외국어"],
        },
        {
            "ruleId": "rule_english_examples_include_ai",
            "topicId": "processing",
            "ruleSummary": "영문 입력 가능 예시에는 AI가 포함된다.",
            "allowed": ["AI, CEO, PD, IT 등 일반화된 영문 약어를 부득이한 경우 쓸 수 있다."],
            "notAllowed": ["영문 약어 예시를 근거로 문장 전체를 영문으로 작성한다."],
            "conditions": ["영문 예시는 입력 허용 범위를 설명하는 예시이지, AI 생성 문장 허용 규정이 아니다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 28), ref(GUIDE, 10)],
            "keywords": ["AI", "영문 입력", "일반화된 명사"],
        },
        {
            "ruleId": "rule_accumulation_decided_by_principal",
            "topicId": "creative_experience",
            "ruleSummary": "누가기록 여부와 방법은 학교장이 정한다.",
            "allowed": ["학교장이 정한 방식에 따라 창체, 일상생활 활동상황, 행특의 누가기록을 운영한다."],
            "notAllowed": ["시도교육감 기준이 현재도 직접 적용된다고 단정한다."],
            "conditions": ["학교별 운영 차이가 있을 수 있으므로 내부 방침을 함께 확인해야 한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 28), ref(OFFICIAL, 158), ref(GUIDE, 10)],
            "keywords": ["누가기록", "학교장", "창체", "행특", "일상생활 활동상황"],
        },
        {
            "ruleId": "rule_no_separate_paper_accumulation_ledger",
            "topicId": "creative_experience",
            "ruleSummary": "누가기록은 교육정보시스템 관리가 원칙이며 별도 종이 대장을 따로 두는 방식이 기본이 아니다.",
            "allowed": ["교육정보시스템 서식 또는 학교 자체 서식을 근거자료와 함께 활용할 수 있다."],
            "notAllowed": ["근거 없이 별도 수기 대장을 공식 기록처럼 운영한다."],
            "conditions": ["학교 자체 서식을 쓰더라도 나이스 반영과 근거자료 관리 체계를 함께 갖춰야 한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 28), ref(CHANGES, slide=15)],
            "keywords": ["누가기록", "교육정보시스템", "나이스", "근거자료"],
        },
        {
            "ruleId": "rule_long_absence_special_note",
            "topicId": "attendance",
            "ruleSummary": "출결 특기사항은 장기결석과 반복적인 지각·조퇴·결과 등을 기준으로 입력한다.",
            "allowed": ["장기결석은 결석 종류별 사유를 입력한다.", "기타결석은 1일이라도 사유를 입력한다."],
            "notAllowed": ["출석인정 결석 사유를 일반적으로 특기사항에 적는다."],
            "conditions": ["장기결석 기준일은 학교장이 7일 전후 범위에서 정할 수 있다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 58), ref(GUIDE, 21), ref(CHANGES, slide=9)],
            "keywords": ["장기결석", "출결 특기사항", "기타결석", "학교장"],
        },
        {
            "ruleId": "rule_attendance_privacy_committee_note_exception",
            "topicId": "attendance",
            "ruleSummary": "질병결석 사유는 개인정보 보호가 필요하면 학업성적관리위원회 심의를 거쳐 입력하지 않을 수 있다.",
            "allowed": ["개인정보 보호가 필요한 질병결석 사유는 심의를 거쳐 생략할 수 있다."],
            "notAllowed": ["민감한 질병 정보를 필요 이상으로 공개한다."],
            "conditions": ["학업성적관리위원회 심의가 필요하다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": True,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 58), ref(GUIDE, 21)],
            "keywords": ["질병결석", "개인정보 보호", "학업성적관리위원회"],
        },
        {
            "ruleId": "rule_other_absence_one_day_note",
            "topicId": "attendance",
            "ruleSummary": "기타결석은 1일이라도 출결 특기사항에 사유를 입력한다.",
            "allowed": ["기타결석이 하루만 있어도 사유를 적는다."],
            "notAllowed": ["기타결석이 짧다는 이유로 사유를 생략한다."],
            "conditions": ["객관적으로 확인 가능한 사유에 근거해 입력한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 58), ref(CHANGES, slide=10)],
            "keywords": ["기타결석", "1일", "출결 특기사항"],
        },
        {
            "ruleId": "rule_tardy_earlyleave_result_note",
            "topicId": "attendance",
            "ruleSummary": "지각·조퇴·결과는 원칙적으로 사유를 입력하지 않되 반복적이거나 잦은 경우에 입력할 수 있다.",
            "allowed": ["반복적이거나 잦은 지각·조퇴·결과는 사유를 입력할 수 있다."],
            "notAllowed": ["지각·조퇴·결과를 모두 기계적으로 특기사항에 적는다."],
            "conditions": ["빈도와 반복성을 학교 기준과 학생 상황에 따라 판단한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 58), ref(GUIDE, 21)],
            "keywords": ["지각", "조퇴", "결과", "반복", "출결 특기사항"],
        },
        {
            "ruleId": "rule_perfect_attendance_exceptions",
            "topicId": "attendance",
            "ruleSummary": "개근은 학적 변동과 특수교육 예외를 확인한 뒤 판단한다.",
            "allowed": ["전입은 전출교와 전입교 출결을 합산해 판단한다.", "재입학은 재입학 전후 출결을 합산해 판단한다."],
            "notAllowed": ["수업일수가 다른 중도 입학·편입 학생에게 기계적으로 개근을 입력한다.", "순회교육학생이나 건강장애학생에게 자동으로 개근을 입력한다."],
            "conditions": ["순회교육학생, 건강장애학생, 원격수업 대상 특수교육대상자는 개근을 공란 처리한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 59), ref(GUIDE, 22), ref(CHANGES, slide=11)],
            "keywords": ["개근", "전입", "재입학", "순회교육학생", "건강장애학생"],
        },
        {
            "ruleId": "rule_subject_attendance_rate_16_sessions",
            "topicId": "attendance",
            "ruleSummary": "과목출석률은 1학점당 수업량 16회의 3분의 2 이상 출석 기준으로 본다.",
            "allowed": ["학점 취득 여부를 판단할 때 1학점당 16회 기준의 3분의 2 이상 출석 기준을 적용한다."],
            "notAllowed": ["실제 운영한 총수업 횟수 기준으로 바뀌었다고 단정한다."],
            "conditions": ["2026학년도에는 1·2학년 과목출석률 질문에서 우선 적용한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, 55), ref(GUIDE, "18~19")],
            "keywords": ["과목출석률", "1학점당 16회", "3분의 2", "1·2학년"],
        },
        {
            "ruleId": "rule_subject_attendance_every_period_nice",
            "topicId": "attendance",
            "ruleSummary": "과목 담당교사는 매시간 학생의 수업 참여 여부를 확인해 나이스에 입력해야 한다.",
            "allowed": ["매시간 수업 참여 여부를 확인해 나이스에 입력한다.", "출석인정 결석과 결과는 출석으로 반영한다."],
            "notAllowed": ["학기 말에 한꺼번에 추정 입력한다."],
            "conditions": ["출석인정 결석 또는 결과 여부도 반영 기준에 맞게 처리해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, 55)],
            "keywords": ["나이스", "매시간", "수업 참여", "출석인정 결석", "출석인정 결과"],
        },
        {
            "ruleId": "rule_awards_only_in_awards_section",
            "topicId": "awards",
            "ruleSummary": "교내상은 수상경력 항목에만 입력하고 다른 항목에 돌려 적지 않는다.",
            "allowed": ["입력 가능한 교내상은 수상경력 항목에 입력한다."],
            "notAllowed": ["대회 준비 과정이나 참가 사실을 세특이나 행특 등 다른 항목에 적는다."],
            "conditions": ["수상 여부와 별개로 참가 사실만 적는 것도 허용되지 않는다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "61~65"), ref(GUIDE, 123)],
            "keywords": ["수상경력", "교내상", "참가 사실", "세특", "행특"],
        },
        {
            "ruleId": "rule_awards_must_follow_school_plan",
            "topicId": "awards",
            "ruleSummary": "학년 초 학교교육계획에 반영된 교내상만 입력할 수 있다.",
            "allowed": ["학년 초 학교교육계획에 반영된 연간 대회와 수상계획에 따른 교내상을 입력한다."],
            "notAllowed": ["학교교육계획에 없는 교내상을 임의로 수상경력에 입력한다."],
            "conditions": ["불가피한 경우 2학기 초 30일 이내 변경계획을 학교장 결재 후 공개해야 한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 65), ref(GUIDE, 24), ref(CHANGES, slide=12)],
            "keywords": ["학교교육계획", "교내상", "2학기 초 30일", "학교장 결재", "변경계획"],
        },
        {
            "ruleId": "rule_no_competition_participation_record",
            "topicId": "awards",
            "ruleSummary": "교내 대회 준비 과정이나 참가 사실만으로는 기록하지 않는다.",
            "allowed": ["실제 입력 대상은 수상경력 항목의 허용된 교내상뿐이다."],
            "notAllowed": ["대회 준비, 참가, 본선 진출 사실만을 다른 항목에 적는다."],
            "conditions": ["수상을 하지 않았더라도 교육활동 평가 문장으로 우회 입력하면 안 된다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "61~65"), ref(GUIDE, 123)],
            "keywords": ["교내대회", "참가 사실", "준비 과정", "수상경력"],
        },
        {
            "ruleId": "rule_certificate_scope",
            "topicId": "certificates",
            "ruleSummary": "입력 가능한 자격은 국가기술자격, 법령상 국가자격, 교육부장관 지정 국가공인 민간자격이다.",
            "allowed": ["국가기술자격", "법령에 따른 국가자격", "교육부장관 지정 국가공인 민간자격"],
            "notAllowed": ["입력 대상이 아닌 일반 민간자격을 자격증 항목에 적는다."],
            "conditions": ["민간자격은 국가공인 여부와 지정 범위를 함께 확인해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "66~68"), ref(GUIDE, 25)],
            "keywords": ["자격증", "국가기술자격", "국가자격", "국가공인 민간자격"],
        },
        {
            "ruleId": "rule_certificate_private_accreditation_check",
            "topicId": "certificates",
            "ruleSummary": "국가공인 민간자격은 공인 유효기간과 급수를 확인해야 한다.",
            "allowed": ["유효한 공인 기간 안의 자격과 해당 급수를 확인한 뒤 입력한다."],
            "notAllowed": ["과거에 공인되었다는 이유만으로 현재 효력이 없는 민간자격을 입력한다."],
            "conditions": ["교육부장관 지정 여부와 함께 공인 상태를 확인해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 68)],
            "keywords": ["국가공인 민간자격", "유효기간", "급수", "교육부장관"],
        },
        {
            "ruleId": "rule_creative_area_names_by_grade",
            "topicId": "creative_experience",
            "ruleSummary": "창의적 체험활동 영역명은 1·2학년과 3학년이 다르다.",
            "allowed": ["1·2학년은 자율·자치활동, 동아리활동, 진로활동을 사용한다.", "3학년은 자율활동, 동아리활동, 봉사활동, 진로활동을 사용한다."],
            "notAllowed": ["1·2학년에 기존 4개 영역명을 그대로 적용한다."],
            "conditions": ["학년을 먼저 확인한 뒤 영역명을 답해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, 77)],
            "keywords": ["창체", "1·2학년", "3학년", "자율·자치활동", "봉사활동"],
        },
        {
            "ruleId": "rule_school_sports_club_name_only",
            "topicId": "creative_experience",
            "ruleSummary": "정규교육과정 이외 학교스포츠클럽은 동아리명만 입력한다.",
            "allowed": ["동아리활동 영역에 학교스포츠클럽 동아리명만 입력한다."],
            "notAllowed": ["활동시간을 함께 입력한다."],
            "conditions": ["필요한 경우 누가기록은 학교스포츠클럽 관리에서 할 수 있고 학교장 사전 승인이 필요하다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, "84~85"), ref(CHANGES, slide=16)],
            "keywords": ["학교스포츠클럽", "동아리명", "활동시간", "학교장 승인"],
        },
        {
            "ruleId": "rule_no_special_note_for_outside_curriculum_sports",
            "topicId": "creative_experience",
            "ruleSummary": "정규교육과정 이외 학교스포츠클럽 특기사항은 입력하지 않는다.",
            "allowed": ["동아리명만 기록한다."],
            "notAllowed": ["정규교육과정 이외 학교스포츠클럽의 특기사항을 창체에 입력한다."],
            "conditions": ["학교스포츠클럽 활동 맥락을 설명할 필요가 있어도 특기사항 항목으로 우회 입력하면 안 된다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, "84~85"), ref(CHANGES, slide=17)],
            "keywords": ["학교스포츠클럽", "특기사항", "정규교육과정 이외"],
        },
        {
            "ruleId": "rule_volunteer_no_simple_donation",
            "topicId": "volunteer_service",
            "ruleSummary": "금품이나 물품의 단순 기부는 봉사활동 실적으로 인정하지 않는다.",
            "allowed": ["실제 봉사활동 수행 시간과 내용을 확인할 수 있는 활동만 입력한다."],
            "notAllowed": ["현금이나 물품 기부를 봉사활동 시간으로 환산한다."],
            "conditions": ["객관적으로 확인 가능한 봉사활동이어야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 87)],
            "keywords": ["봉사활동", "기부", "금품", "물품"],
        },
        {
            "ruleId": "rule_volunteer_eight_hours_per_day",
            "topicId": "volunteer_service",
            "ruleSummary": "봉사활동은 1일 8시간 이내 인정이 원칙이다.",
            "allowed": ["동일 일자의 봉사활동은 원칙적으로 8시간 이내로 인정한다."],
            "notAllowed": ["하루 봉사 시간을 무제한 합산한다."],
            "conditions": ["헌혈 등 별도 예외가 있는 경우는 해당 기준을 따른다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 88)],
            "keywords": ["봉사활동", "1일 8시간", "헌혈"],
        },
        {
            "ruleId": "rule_volunteer_curricular_link_grades_1_2",
            "topicId": "volunteer_service",
            "ruleSummary": "1·2학년의 정규교육과정 내 봉사활동은 창체 각 영역과 연계해 기록할 수 있다.",
            "allowed": ["학교교육계획에 따른 정규교육과정 내 봉사활동은 창체 누가기록에서 입력할 수 있다."],
            "notAllowed": ["1·2학년의 정규교육과정 내 봉사활동을 기존 3학년 방식만으로 설명한다."],
            "conditions": ["정규교육과정 외 봉사활동과 학생 개인계획 봉사활동은 기존처럼 봉사활동실적관리 메뉴를 사용한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, "86~90"), ref(GUIDE, 125)],
            "keywords": ["1·2학년", "봉사활동", "창체", "정규교육과정"],
        },
        {
            "ruleId": "rule_no_duplicate_volunteer_time_grade_3",
            "topicId": "volunteer_service",
            "ruleSummary": "3학년의 봉사활동 시간은 다른 창체 영역 시간과 중복 인정하지 않는다.",
            "allowed": ["3학년은 기존 봉사활동 영역 체계에 따라 봉사 시간을 관리한다."],
            "notAllowed": ["같은 시간을 봉사활동과 다른 창체 영역 시간으로 중복 계산한다."],
            "conditions": ["3학년은 기존 4개 영역 체계를 따른다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grade_3",
            "sourceRefs": [ref(OFFICIAL, 90)],
            "keywords": ["3학년", "봉사활동", "중복 인정", "창체"],
        },
        {
            "ruleId": "rule_subject_notes_for_all_students",
            "topicId": "subject_progress",
            "ruleSummary": "세특은 모든 학생 입력이 원칙이다.",
            "allowed": ["모든 학생에 대해 과목별 세부능력 및 특기사항을 입력한다."],
            "notAllowed": ["일부 학생에게만 세특을 입력하고 나머지는 비워 둔다."],
            "conditions": ["수업과 평가 과정에서 확인한 학생의 성장과 특성을 바탕으로 작성해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "95, 126"), ref(GUIDE, 63)],
            "keywords": ["세특", "모든 학생", "교과학습발달상황"],
        },
        {
            "ruleId": "rule_subject_notes_special_none_with_committee",
            "topicId": "subject_progress",
            "ruleSummary": "부득이한 경우에만 학업성적관리위원회 심의를 거쳐 특이사항 없음으로 입력할 수 있다.",
            "allowed": ["정당한 사유가 있고 심의를 거친 경우 특이사항 없음으로 입력할 수 있다."],
            "notAllowed": ["편의상 세특을 비우거나 특이사항 없음으로 일괄 입력한다."],
            "conditions": ["학업성적관리위원회 심의가 필요하다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": True,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "95, 126"), ref(GUIDE, 63), ref(CHANGES, slide=44)],
            "keywords": ["특이사항 없음.", "세특", "학업성적관리위원회"],
        },
        {
            "ruleId": "rule_small_class_rank_marker_by_grade",
            "topicId": "subject_progress",
            "ruleSummary": "소인수 과목의 석차등급 또는 점 표시 기준은 학년에 따라 다르다.",
            "allowed": ["1·2학년은 수강자 수 5명 이하일 때 석차등급 또는 점 중 하나를 같은 과목에 동일하게 적용한다.", "3학년은 수강자 수 13명 이하일 때 같은 기준을 적용한다."],
            "notAllowed": ["같은 과목 안에서 학생별로 석차등급과 점 표기를 섞어 쓴다."],
            "conditions": ["같은 학년, 같은 과목에는 동일한 표기 방식을 적용한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "95, 126"), ref(GUIDE, 140)],
            "keywords": ["소인수 과목", "석차등급", "점", "1·2학년", "3학년"],
        },
        {
            "ruleId": "rule_online_content_in_bigo",
            "topicId": "subject_progress",
            "ruleSummary": "온라인 콘텐츠로 이수한 경우는 비고란에 온라인 콘텐츠라고 입력한다.",
            "allowed": ["온라인 콘텐츠 이수 사실은 비고란에 온라인 콘텐츠라고 적는다."],
            "notAllowed": ["온라인 콘텐츠 이수 사실을 세특 본문에 길게 서술한다."],
            "conditions": ["공동교육과정, 온라인학교, 학교 밖 교육 등 다른 비고 항목과 구분해 처리한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "94, 97"), ref(CHANGES, slide=43)],
            "keywords": ["온라인 콘텐츠", "비고란", "공동교육과정"],
        },
        {
            "ruleId": "rule_regular_exam_term_usage",
            "topicId": "subject_progress",
            "ruleSummary": "현행 용어는 지필평가가 아니라 정기시험이다.",
            "allowed": ["정기시험과 수행평가라는 용어를 사용한다."],
            "notAllowed": ["현행 기준 설명에서 지필평가라는 표현을 기본 용어로 쓴다."],
            "conditions": ["기존 문서 표현을 인용할 때도 현재 용어로 다시 설명해 주는 것이 좋다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, 97), ref(TRAINING, slide=7)],
            "keywords": ["정기시험", "지필평가", "수행평가"],
        },
        {
            "ruleId": "rule_performance_assessment_no_homework_or_memorization",
            "topicId": "subject_progress",
            "ruleSummary": "과제형 또는 단순 암기식 수행평가는 지양해야 한다.",
            "allowed": ["수업 중 관찰과 과정 중심 평가를 수행평가에 반영한다."],
            "notAllowed": ["과제를 집에서 대신 수행하게 하거나 단순 암기만 확인하는 방식으로 운영한다."],
            "conditions": ["수업과 평가의 직접 연계가 분명해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "101, 132"), ref(TRAINING, slide=7)],
            "keywords": ["수행평가", "과제형", "암기식", "과정 중심"],
        },
        {
            "ruleId": "rule_performance_assessment_ai_caution",
            "topicId": "subject_progress",
            "ruleSummary": "수행평가에서 생성형 AI 활용은 사전 안내, 금지 범위 설정, 교사 직접 관찰 원칙이 필요하다.",
            "allowed": ["학교가 사전에 허용 범위와 금지 범위를 안내한 범위 안에서 활용 여부를 관리한다."],
            "notAllowed": ["AI 결과물을 학생의 실제 수행으로 간주해 평가한다.", "교사의 직접 관찰 없이 AI 산출물만으로 수행평가를 마친다."],
            "conditions": ["평가의 공정성과 신뢰도를 우선 확보해야 한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "101, 132"), ref(TRAINING, slide=7), ref(TRAINING, slide=132)],
            "keywords": ["수행평가", "생성형 AI", "사전 안내", "공정성", "직접 관찰"],
        },
        {
            "ruleId": "rule_reading_duplicate_allowed_with_distinct_evidence",
            "topicId": "reading",
            "ruleSummary": "같은 도서라도 증빙자료와 기록 맥락이 다르면 중복 입력할 수 있다.",
            "allowed": ["과목, 학년, 학기, 영역이 다르고 증빙자료가 다르면 같은 도서를 각각 입력한다.", "원서와 번역본도 증빙이 다르면 각각 입력할 수 있다."],
            "notAllowed": ["증빙자료 차이 없이 같은 도서를 반복 입력한다."],
            "conditions": ["기록 맥락과 증빙자료가 분명해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "156~157"), ref(GUIDE, 152)],
            "keywords": ["독서활동상황", "동일 도서", "중복 입력", "증빙자료"],
        },
        {
            "ruleId": "rule_behavior_excludes_forbidden_content",
            "topicId": "behavior",
            "ruleSummary": "행특에는 다른 항목에 적을 수 없는 내용을 우회 입력하지 않는다.",
            "allowed": ["학교 교육활동 전반에서 지속적으로 관찰한 학생의 성장과 특성을 교육적 관점에서 입력한다."],
            "notAllowed": ["방과후학교 활동 등 다른 항목에도 적을 수 없는 내용을 행특에 적는다."],
            "conditions": ["부정적 행동특성을 입력할 때는 구체적인 누가기록을 바탕으로 하는 것이 바람직하다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "158~159"), ref(GUIDE, 154), ref(CHANGES, slide=50)],
            "keywords": ["행특", "방과후학교", "교육적 관점", "누가기록"],
        },
        {
            "ruleId": "rule_correction_requires_objective_evidence",
            "topicId": "corrections",
            "ruleSummary": "마감 후 정정은 같은 학년도 객관적 증빙자료가 있어야 한다.",
            "allowed": ["해당 학년도에 생산된 객관적 증빙자료를 바탕으로 정정한다."],
            "notAllowed": ["기억이나 추정만으로 마감 후 기록을 수정한다."],
            "conditions": ["증빙자료는 적정한 입력 주체가 만든 자료여야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": True,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 165), ref(GUIDE, 156)],
            "keywords": ["정정", "객관적 증빙자료", "같은 학년도", "입력 주체"],
        },
        {
            "ruleId": "rule_correction_swapped_items_committee",
            "topicId": "corrections",
            "ruleSummary": "서술형 항목이 서로 바뀌었거나 누락된 경우는 학업성적관리위원회 심의를 거쳐 정정할 수 있다.",
            "allowed": ["입력 주체의 과실로 서술형 항목이 서로 바뀌거나 통째로 누락된 경우 정정한다."],
            "notAllowed": ["주관적 판단만으로 학생 간 서술형 항목을 바꿔 고친다."],
            "conditions": ["객관적 증빙자료를 갖추고 학업성적관리위원회 심의를 거쳐야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": True,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "165~166"), ref(GUIDE, 156)],
            "keywords": ["정정", "서술형 항목", "입력 주체 과실", "학업성적관리위원회"],
        },
        {
            "ruleId": "rule_preserve_records_electronically",
            "topicId": "corrections",
            "ruleSummary": "학교생활기록부는 전자보존이 원칙이다.",
            "allowed": ["학교생활기록부 I·II를 전자적으로 준영구 보존한다."],
            "notAllowed": ["학생용 출력물을 별도의 영구 장부처럼 운영한다."],
            "conditions": ["학교에서는 졸업 후 8년간 보관한 뒤 전자적으로 보존한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 163)],
            "keywords": ["전자보존", "준영구", "졸업 후 8년", "학교생활기록부 I·II"],
        },
        {
            "ruleId": "rule_commercial_use_banned",
            "topicId": "processing",
            "ruleSummary": "학교생활기록부와 관련 자료의 상업적 이용은 제한된다.",
            "allowed": ["법령과 지침 범위 안의 교육 목적 활용만 검토한다."],
            "notAllowed": ["영리 목적 서비스 개선, 마케팅, 홍보 등에 학교생활기록부를 활용한다."],
            "conditions": ["외부 제공 또는 재활용 가능 여부는 상업적 이용 제한 조항을 먼저 확인해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 174), ref(GUIDE, 72)],
            "keywords": ["상업적 이용", "활용 제한", "영리 목적"],
        },
        {
            "ruleId": "rule_evaluation_management_center_operation",
            "topicId": "processing",
            "ruleSummary": "평가관리센터 설치·운영 조항에 따라 평가와 기록 관리 체계를 갖춰야 한다.",
            "allowed": ["학교는 평가와 기록 관리를 위한 체계적 운영 장치를 둘 수 있다."],
            "notAllowed": ["평가와 기록 관리 책임을 비공식적으로만 처리한다."],
            "conditions": ["구체적 운영은 학교의 관리 체계 안에서 정리해야 한다."],
            "schoolRuleNeeded": True,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 174), ref(GUIDE, 72)],
            "keywords": ["평가관리센터", "설치", "운영", "관리 체계"],
        },
    ]


def build_qa_cards() -> list[dict]:
    return [
        {
            "qaId": "qa_processing_hanja_input",
            "topicId": "processing",
            "question": "한자 표기가 많은 중국어, 한문 등의 과목에서는 세특 일부를 한자로 입력할 수 있나요?",
            "answer": "불가합니다. 학교생활기록부 문자는 한글이 원칙이고 부득이한 경우에만 영문을 사용할 수 있으므로, 한자를 포함한 다른 외국어 표기는 입력할 수 없습니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 28), ref(GUIDE, 92)],
            "keywords": ["한자", "영문", "처리요령", "세특"],
        },
        {
            "qaId": "qa_processing_ai_polish",
            "topicId": "processing",
            "question": "교사가 세특 문장을 다듬을 때 생성형 AI 도움을 받아도 되나요?",
            "answer": "보조 수단으로 참고하는 것 자체를 곧바로 금지한다고 보기는 어렵지만, AI가 만든 문장을 검토 없이 그대로 입력하면 안 됩니다. 최종 문장과 사실관계는 반드시 교사가 직접 확인해야 합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 19), ref(TRAINING, slide=23)],
            "keywords": ["생성형 AI", "세특", "교사 확인", "직접 입력"],
        },
        {
            "qaId": "qa_accumulation_principal_policy",
            "topicId": "creative_experience",
            "question": "창체나 행특의 누가기록은 꼭 해야 하나요?",
            "answer": "학교마다 다를 수 있습니다. 누가기록 여부와 방법은 학교장이 정하므로, 해당 학교의 운영 방침을 먼저 확인해야 합니다. 다만 누가기록은 보조 자료이므로, 입력 주체가 직접 관찰한 학생 특성은 누가기록에 없더라도 입력할 수 있습니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades_with_school_policy_check",
            "sourceRefs": [ref(OFFICIAL, 28), ref(GUIDE, 93)],
            "keywords": ["누가기록", "학교장", "창체", "행특"],
        },
        {
            "qaId": "qa_retention_vs_graduation_deferral",
            "topicId": "personal_school_status",
            "question": "유급과 졸업유예는 어떻게 다른가요?",
            "answer": "유급은 해당 학년 교육과정을 마치지 못해 상급 학년으로 진급하지 못하는 경우입니다. 졸업유예는 출석일수는 충족했지만 졸업에 필요한 학점을 모두 취득하지 못해 졸업 자격을 얻지 못한 경우입니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "graduation_stage",
            "sourceRefs": [ref(OFFICIAL, "34~35"), ref(GUIDE, "11~13")],
            "keywords": ["유급", "졸업유예", "진급", "졸업 자격"],
        },
        {
            "qaId": "qa_subject_attendance_recognized_absence",
            "topicId": "attendance",
            "question": "출석인정 결석이나 출석인정 결과도 과목출석률에서 출석으로 보나요?",
            "answer": "네. 과목출석률에서는 출석인정 결석과 출석인정 결과를 출석으로 반영합니다. 다만 과목 담당교사는 매시간 학생의 수업 참여 여부를 확인해 나이스에 입력해야 합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, 55)],
            "keywords": ["과목출석률", "출석인정 결석", "출석인정 결과", "나이스"],
        },
        {
            "qaId": "qa_attendance_reference_witness_and_juvenile_case",
            "topicId": "attendance",
            "question": "학생이 참고인 조사나 소년보호재판 출석 때문에 결석한 경우는 어떻게 처리하나요?",
            "answer": "참고인 조사 출석은 곧바로 미인정결석으로 단정하지 않습니다. 학생 상황과 교육적 목적을 고려해 학교가 출석인정 결석 또는 기타결석으로 판단할 수 있습니다. 반면 학생 자신이 범죄행위와 관련해 소년보호재판에 출석한 경우에는 해당 기간을 출석인정 결석으로 처리합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(GUIDE, 106)],
            "keywords": ["참고인 조사", "소년보호재판", "출석인정 결석", "기타결석"],
        },
        {
            "qaId": "qa_awards_competition_participation",
            "topicId": "awards",
            "question": "교내대회 참가 사실이나 학교 계획에 없던 교내상은 학교생활기록부에 적을 수 있나요?",
            "answer": "적을 수 없습니다. 교내대회 준비 과정이나 참가 사실만으로는 수상경력 외 다른 항목에 기록할 수 없고, 학교교육계획에 반영되지 않은 교내상도 수상경력에 입력할 수 없습니다. 다만 불가피한 경우에는 2학기 초 30일 이내 변경계획을 학교장 결재 후 공개했는지부터 확인해야 합니다.",
            "answerPolicy": "recordability",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "61~65"), ref(GUIDE, 123)],
            "keywords": ["교내대회", "참가 사실", "학교교육계획", "수상경력"],
        },
        {
            "qaId": "qa_certificate_private_license",
            "topicId": "certificates",
            "question": "국가공인 민간자격증이면 모두 입력할 수 있나요?",
            "answer": "아닙니다. 국가공인 민간자격증 가운데서도 교육부장관이 지정한 자격만 입력 대상입니다. 공인 유효기간과 급수도 함께 확인해야 합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "66~68")],
            "keywords": ["국가공인 민간자격", "교육부장관", "유효기간", "급수"],
        },
        {
            "qaId": "qa_creative_area_difference_by_grade",
            "topicId": "creative_experience",
            "question": "2026학년도 창체 영역명은 1·2학년과 3학년이 같은가요?",
            "answer": "같지 않습니다. 1·2학년은 자율·자치활동, 동아리활동, 진로활동의 3개 영역을 사용하고, 3학년은 기존의 자율활동, 동아리활동, 봉사활동, 진로활동 4개 영역을 사용합니다.",
            "answerPolicy": "grade_difference",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, 77)],
            "keywords": ["창체", "1·2학년", "3학년", "영역명"],
        },
        {
            "qaId": "qa_school_sports_club_record",
            "topicId": "creative_experience",
            "question": "정규교육과정 이외 학교스포츠클럽 활동은 창체에 어떻게 기록하나요?",
            "answer": "동아리활동 영역에 클럽명만 입력합니다. 활동시간은 적지 않고, 특기사항도 입력하지 않습니다. 필요한 경우 누가기록은 학교스포츠클럽 관리에서 할 수 있지만 학교장 사전 승인이 필요합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, "84~85"), ref(CHANGES, slide=16)],
            "keywords": ["학교스포츠클럽", "동아리명", "활동시간", "특기사항", "학교장 승인"],
        },
        {
            "qaId": "qa_volunteer_curricular_grade_1_2",
            "topicId": "volunteer_service",
            "question": "2026학년도 1·2학년의 봉사활동은 창체에 적나요, 봉사활동실적관리에 적나요?",
            "answer": "둘로 나눠 봐야 합니다. 학교교육계획에 따른 정규교육과정 내 봉사활동은 창체 각 영역의 누가기록에서 입력할 수 있고, 정규교육과정 외 봉사활동과 학생 개인계획 봉사활동은 기존처럼 봉사활동실적관리 메뉴에서 입력합니다. 3학년은 기존 체계를 따릅니다.",
            "answerPolicy": "grade_difference",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "86~90"), ref(GUIDE, 125)],
            "keywords": ["봉사활동", "창체", "봉사활동실적관리", "1·2학년", "3학년"],
        },
        {
            "qaId": "qa_volunteer_simple_donation",
            "topicId": "volunteer_service",
            "question": "물품이나 금전 기부를 봉사활동 시간으로 입력할 수 있나요?",
            "answer": "없습니다. 금품이나 물품의 단순 기부는 봉사활동 실적으로 인정하지 않습니다.",
            "answerPolicy": "recordability",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 87)],
            "keywords": ["봉사활동", "기부", "금품", "물품"],
        },
        {
            "qaId": "qa_subject_small_class_rank_rule",
            "topicId": "subject_progress",
            "question": "석차등급을 산출하는 과목에서 석차등급과 점 표기 중 무엇을 쓸지는 어떻게 정하나요?",
            "answer": "학년에 따라 다릅니다. 1·2학년은 수강자 수 5명 이하인 경우, 3학년은 수강자 수 13명 이하인 경우 같은 학년의 같은 과목에 대해 석차등급 또는 점 중 한 가지 방식을 동일하게 적용합니다.",
            "answerPolicy": "grade_difference",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "95, 126"), ref(GUIDE, 140)],
            "keywords": ["소인수 과목", "석차등급", "점", "1·2학년", "3학년"],
        },
        {
            "qaId": "qa_subject_special_none",
            "topicId": "subject_progress",
            "question": "세특을 쓰기 어려운 경우 그냥 특이사항 없음으로 입력해도 되나요?",
            "answer": "원칙은 모든 학생 입력입니다. 부득이한 경우에만 학업성적관리위원회 심의를 거쳐 특이사항 없음으로 입력할 수 있습니다.",
            "answerPolicy": "recordability",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "95, 126"), ref(GUIDE, 63)],
            "keywords": ["세특", "특이사항 없음.", "모든 학생", "학업성적관리위원회"],
        },
        {
            "qaId": "qa_online_content_bigo",
            "topicId": "subject_progress",
            "question": "온라인 콘텐츠로 이수한 과목은 어디에 어떻게 표시하나요?",
            "answer": "비고란에 온라인 콘텐츠라고 입력합니다. 이수 사실을 세특 본문에 길게 설명하는 방식이 기본은 아닙니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, 97), ref(CHANGES, slide=43)],
            "keywords": ["온라인 콘텐츠", "비고란", "세특"],
        },
        {
            "qaId": "qa_regular_exam_term",
            "topicId": "subject_progress",
            "question": "지금도 지필평가라는 용어를 써도 되나요?",
            "answer": "현행 기준 설명에서는 정기시험이라는 용어를 쓰는 것이 맞습니다. 수행평가와 함께 현재 용어 체계로 설명해 주세요.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, 97), ref(TRAINING, slide=7)],
            "keywords": ["정기시험", "지필평가", "수행평가"],
        },
        {
            "qaId": "qa_performance_assessment_ai",
            "topicId": "subject_progress",
            "question": "수행평가에서 학생의 생성형 AI 활용을 허용해도 되나요?",
            "answer": "한 문장으로 허용 또는 금지라고 답하기 어렵습니다. 학교는 수행평가의 공정성과 신뢰도를 해치지 않도록 허용 범위와 금지 범위를 사전에 안내해야 하고, 교사의 직접 관찰과 확인이 가능한 방식으로 운영해야 합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "grades_1_2_vs_grade_3",
            "sourceRefs": [ref(OFFICIAL, "101, 132"), ref(TRAINING, slide=7)],
            "keywords": ["수행평가", "생성형 AI", "사전 안내", "공정성", "직접 관찰"],
        },
        {
            "qaId": "qa_reading_same_book_duplication",
            "topicId": "reading",
            "question": "같은 책을 국어와 과학에서 서로 다른 관점으로 읽고 다른 독서 증빙자료가 있다면 독서활동상황에 중복 기재할 수 있나요?",
            "answer": "가능합니다. 같은 도서라도 과목, 학년, 학기, 영역이 다르거나 증빙자료가 다르면 각각 입력할 수 있습니다. 원서와 번역본도 증빙이 다르면 각각 입력할 수 있습니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "156~157"), ref(GUIDE, 152)],
            "keywords": ["독서", "동일 도서", "중복 기재", "증빙자료"],
        },
        {
            "qaId": "qa_behavior_after_school",
            "topicId": "behavior",
            "question": "방과후학교 활동 내용을 행특에 적을 수 있나요?",
            "answer": "적을 수 없습니다. 방과후학교 활동 등 다른 항목에도 적을 수 없는 내용은 행특에도 우회 입력할 수 없습니다.",
            "answerPolicy": "recordability",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 159), ref(GUIDE, 154)],
            "keywords": ["행특", "방과후학교", "우회 입력"],
        },
        {
            "qaId": "qa_correction_swapped_descriptive_items",
            "topicId": "corrections",
            "question": "이전 학년의 세특이나 진로활동 특기사항이 학생끼리 서로 바뀌었거나 통째로 누락된 경우 정정할 수 있나요?",
            "answer": "가능합니다. 객관적 증빙자료가 있고 입력 주체의 과실이 확인되면 학업성적관리위원회 심의를 거쳐 정정할 수 있습니다. 먼저 해당 교사의 확인과 증빙자료의 적정성을 함께 점검해야 합니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, "165~166"), ref(GUIDE, 156)],
            "keywords": ["정정", "세특", "진로활동", "과실", "학업성적관리위원회"],
        },
        {
            "qaId": "qa_correction_student_info_exception",
            "topicId": "corrections",
            "question": "학생 이름이나 주민등록번호 같은 학생정보도 학업성적관리위원회 심의를 거쳐야만 정정할 수 있나요?",
            "answer": "학생정보 정정은 예외가 있습니다. 학생정보는 객관적 증빙자료로 확인되면 학교장이 위원회 심의 없이 정정할 수 있습니다.",
            "answerPolicy": "qa_lookup",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 166), ref(GUIDE, 157)],
            "keywords": ["학생정보", "정정", "학교장", "위원회 예외"],
        },
        {
            "qaId": "qa_commercial_use",
            "topicId": "processing",
            "question": "학교생활기록부 자료를 상업적 서비스 학습자료나 홍보자료로 써도 되나요?",
            "answer": "안 됩니다. 학교생활기록부와 관련 자료의 상업적 이용은 제한되므로 영리 목적 활용을 전제로 답변하거나 재사용해서는 안 됩니다.",
            "answerPolicy": "recordability",
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 174), ref(GUIDE, 72)],
            "keywords": ["상업적 이용", "영리 목적", "학교생활기록부"],
        },
    ]


def enrich_change_cards(records: list[dict]) -> list[dict]:
    for record in records:
        if record["changeId"] == "chg_2026_002_retention_definition":
            record["sourceRefs"] = [
                ref(OFFICIAL, 34),
                ref(GUIDE, "12~13"),
                ref(CHANGES, slide=5),
            ]
    return records


def enrich_rule_cards(records: list[dict]) -> list[dict]:
    title_map = {
        "rule_teacher_owns_descriptive_items": "서술형 항목은 교사가 직접 작성",
        "rule_no_direct_ai_generated_text": "AI 생성 문장 직접 입력 금지",
        "rule_input_based_on_direct_observation": "직접 관찰과 평가에 근거한 입력",
        "rule_hangul_default_english_only": "한글이 원칙이고 영문은 예외",
        "rule_english_examples_include_ai": "영문 입력 허용 예시에 AI 포함",
        "rule_accumulation_decided_by_principal": "누가기록 여부와 방법은 학교장이 결정",
        "rule_no_separate_paper_accumulation_ledger": "누가기록은 교육정보시스템 중심으로 관리",
        "rule_long_absence_special_note": "출결 특기사항은 장기결석 중심으로 입력",
        "rule_attendance_privacy_committee_note_exception": "질병결석 사유는 개인정보 보호 예외 가능",
        "rule_other_absence_one_day_note": "기타결석은 1일이라도 입력",
        "rule_tardy_earlyleave_result_note": "반복적인 지각·조퇴·결과만 사유 입력 가능",
        "rule_perfect_attendance_exceptions": "개근은 학적 변동과 특수상황 예외를 확인",
        "rule_subject_attendance_rate_16_sessions": "과목출석률은 1학점당 16회 기준",
        "rule_subject_attendance_every_period_nice": "과목 담당교사는 매시간 나이스 입력",
        "rule_awards_only_in_awards_section": "교내상은 수상경력 항목에만 입력",
        "rule_awards_must_follow_school_plan": "교내상은 학교교육계획에 따른 경우만 입력",
        "rule_no_competition_participation_record": "대회 참가 사실만으로는 기록 불가",
        "rule_certificate_scope": "입력 가능한 자격증 범위",
        "rule_certificate_private_accreditation_check": "민간자격은 공인 상태와 급수 확인",
        "rule_creative_area_names_by_grade": "창체 영역명은 학년별로 다름",
        "rule_school_sports_club_name_only": "정규교육과정 이외 학교스포츠클럽은 동아리명만 입력",
        "rule_no_special_note_for_outside_curriculum_sports": "정규교육과정 이외 학교스포츠클럽 특기사항 미입력",
        "rule_volunteer_no_simple_donation": "단순 기부는 봉사활동으로 인정하지 않음",
        "rule_volunteer_eight_hours_per_day": "봉사활동은 1일 8시간 이내 인정",
        "rule_volunteer_curricular_link_grades_1_2": "1·2학년 정규교육과정 내 봉사활동은 창체 연계 가능",
        "rule_no_duplicate_volunteer_time_grade_3": "3학년 봉사활동 시간은 다른 창체 영역과 중복 불가",
        "rule_subject_notes_for_all_students": "세특은 모든 학생 입력이 원칙",
        "rule_subject_notes_special_none_with_committee": "특이사항 없음은 심의 후 예외적으로만 사용",
        "rule_small_class_rank_marker_by_grade": "소인수 과목의 석차등급 또는 점 표기 기준",
        "rule_online_content_in_bigo": "온라인 콘텐츠는 비고란에 표시",
        "rule_regular_exam_term_usage": "현행 용어는 정기시험",
        "rule_performance_assessment_no_homework_or_memorization": "과제형·암기식 수행평가 지양",
        "rule_performance_assessment_ai_caution": "수행평가의 생성형 AI 활용은 사전 안내와 직접 관찰 필요",
        "rule_reading_duplicate_allowed_with_distinct_evidence": "독서는 증빙이 다르면 같은 책도 각각 입력 가능",
        "rule_behavior_excludes_forbidden_content": "행특에는 금지된 내용을 우회 입력하지 않음",
        "rule_correction_requires_objective_evidence": "정정은 객관적 증빙자료가 있어야 가능",
        "rule_correction_swapped_items_committee": "서술형 항목 뒤바뀜은 심의를 거쳐 정정",
        "rule_preserve_records_electronically": "학교생활기록부는 전자보존이 원칙",
        "rule_commercial_use_banned": "학교생활기록부의 상업적 이용 제한",
        "rule_evaluation_management_center_operation": "평가관리센터 설치·운영 체계 반영",
    }

    by_id: dict[str, dict] = {}
    for record in records:
        record["title"] = title_map.get(record["ruleId"], record.get("title") or record["ruleSummary"])
        by_id[record["ruleId"]] = record

    def clone_rule(source_id: str, new_id: str, title: str) -> dict:
        cloned = json.loads(json.dumps(by_id[source_id], ensure_ascii=False))
        cloned["ruleId"] = new_id
        cloned["title"] = title
        return cloned

    extra_rules = [
        clone_rule("rule_certificate_scope", "rule_certificate_only_designated_scope", "자격증 입력 범위는 지정된 대상에 한정"),
        clone_rule("rule_subject_notes_special_none_with_committee", "rule_subject_notes_special_none", "특이사항 없음은 심의 후 예외적으로만 사용"),
        clone_rule("rule_online_content_in_bigo", "rule_online_content_remark", "온라인 콘텐츠 이수는 비고란에 입력"),
        clone_rule("rule_regular_exam_term_usage", "rule_regular_exam_term", "현행 용어는 정기시험"),
        clone_rule("rule_reading_duplicate_allowed_with_distinct_evidence", "rule_reading_same_book_different_evidence", "같은 책도 증빙이 다르면 각각 입력 가능"),
        {
            "ruleId": "rule_behavior_300_chars",
            "topicId": "behavior",
            "title": "행동특성 및 종합의견은 300자 이내",
            "ruleSummary": "행동특성 및 종합의견은 300자 이내로 입력한다.",
            "allowed": ["교육적 관점의 핵심 사례를 300자 이내로 간결하게 입력한다."],
            "notAllowed": ["기존 500자 기준으로 길게 작성한다.", "분량을 초과한 장문을 입력한다."],
            "conditions": ["현재 글자 수 기준은 300자다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 208), ref(CHANGES, slide=52)],
            "keywords": ["행특", "행동특성 및 종합의견", "300자"],
        },
        {
            "ruleId": "rule_career_activity_500_chars",
            "topicId": "creative_experience",
            "title": "진로활동 특기사항은 500자 이내",
            "ruleSummary": "진로활동 특기사항은 500자 이내로 입력한다.",
            "allowed": ["진로활동의 핵심 내용만 500자 이내로 정리한다."],
            "notAllowed": ["기존 700자 기준으로 장문을 작성한다."],
            "conditions": ["분량보다 핵심 활동과 성장의 압축이 중요하다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 208), ref(CHANGES, slide=52)],
            "keywords": ["진로활동", "특기사항", "500자"],
        },
        {
            "ruleId": "rule_volunteer_content_50_chars",
            "topicId": "volunteer_service",
            "title": "봉사활동 활동내용은 50자 이내",
            "ruleSummary": "봉사활동 실적의 활동내용은 50자 이내로 간략하게 입력한다.",
            "allowed": ["활동내용을 객관적인 사실 중심으로 50자 이내로 적는다."],
            "notAllowed": ["활동 소감문처럼 길게 서술한다.", "기존 250자 기준으로 적는다."],
            "conditions": ["사실 위주로 짧게 적는 것이 원칙이다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "all_grades",
            "sourceRefs": [ref(OFFICIAL, 208), ref(CHANGES, slide=52)],
            "keywords": ["봉사활동", "활동내용", "50자"],
        },
        {
            "ruleId": "rule_grade_1_2_credit_5_grade",
            "topicId": "subject_progress_grades_1_2",
            "title": "1·2학년은 학점·5등급·성취도별 분포비율 체계",
            "ruleSummary": "1·2학년 교과학습발달상황은 학점, 5등급, 성취도와 성취도별 분포비율을 기준으로 본다.",
            "allowed": ["1·2학년 답변에서는 학점과 5등급 체계를 기준으로 설명한다."],
            "notAllowed": ["1·2학년 설명에 단위수와 9등급 체계를 섞는다."],
            "conditions": ["2026학년도 1·2학년은 2022 개정 교육과정 체계로 본다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grades_1_2",
            "sourceRefs": [ref(OFFICIAL, 93), ref(GUIDE, "52~53")],
            "keywords": ["1·2학년", "학점", "5등급", "성취도", "성취도별 분포비율"],
        },
        {
            "ruleId": "rule_grade_3_unit_9_grade",
            "topicId": "subject_progress_grade_3",
            "title": "3학년은 단위수·9등급 체계",
            "ruleSummary": "3학년 교과학습발달상황은 단위수와 9등급 체계를 유지한다.",
            "allowed": ["3학년 답변에서는 단위수와 9등급 기준으로 설명한다."],
            "notAllowed": ["3학년 설명에 학점과 5등급 체계를 섞는다."],
            "conditions": ["3학년은 기존 교육과정 체계를 따른다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "grade_3",
            "sourceRefs": [ref(OFFICIAL, 124), ref(GUIDE, "52~53")],
            "keywords": ["3학년", "단위수", "9등급"],
        },
        {
            "ruleId": "rule_retention_vs_graduation_deferral",
            "topicId": "personal_school_status",
            "title": "유급과 졸업유예는 구분해서 설명",
            "ruleSummary": "유급은 진급 불가이고, 졸업유예는 졸업 학점 미충족으로 졸업 자격을 얻지 못한 상태다.",
            "allowed": ["유급은 해당 학년 미수료, 졸업유예는 졸업 학점 미충족으로 나누어 설명한다."],
            "notAllowed": ["유급과 졸업유예를 같은 의미로 답한다."],
            "conditions": ["진급 문제인지 졸업 자격 문제인지 먼저 구분해야 한다."],
            "schoolRuleNeeded": False,
            "committeeNeeded": False,
            "gradeScope": "graduation_stage",
            "sourceRefs": [ref(OFFICIAL, "34~35"), ref(GUIDE, "12~13")],
            "keywords": ["유급", "졸업유예", "진급", "졸업 자격", "학점"],
        },
    ]

    for extra in extra_rules:
        if extra["ruleId"] not in by_id:
            records.append(extra)
            by_id[extra["ruleId"]] = extra

    return records


def build_test_questions() -> dict:
    return {
        "schemaVersion": "2026-06-17.curated.v2",
        "tests": [
            {
                "testId": "t01",
                "question": "교내대회 참가 사실을 행특이나 세특에 적을 수 있나요?",
                "expectedTopicIds": ["awards", "behavior"],
                "expectedPolicyId": "recordability",
                "mustMention": ["수상경력 외 다른 항목에는 적지 않음", "참가 사실과 준비 과정은 기록 불가"],
                "shouldUseCards": ["rule_awards_only_in_awards_section", "qa_awards_competition_participation"],
            },
            {
                "testId": "t02",
                "question": "학생이 써 온 세특 문장을 교사가 그대로 붙여 넣어도 되나요?",
                "expectedTopicIds": ["processing", "subject_progress"],
                "expectedPolicyId": "recordability",
                "mustMention": ["교사가 직접 작성해야 함", "학생 작성 문장을 그대로 입력하면 안 됨"],
                "shouldUseCards": ["rule_teacher_owns_descriptive_items", "rule_no_direct_ai_generated_text"],
            },
            {
                "testId": "t03",
                "question": "1학년 봉사활동은 창체에 적나요, 봉사활동실적관리에 적나요?",
                "expectedTopicIds": ["volunteer_service", "creative_experience"],
                "expectedPolicyId": "grade_difference",
                "mustMention": ["1·2학년과 3학년 구분", "정규교육과정 내 봉사활동은 창체 연계", "정규교육과정 외와 개인계획 봉사활동은 봉사활동실적관리"],
                "shouldUseCards": ["rule_volunteer_curricular_link_grades_1_2", "qa_volunteer_curricular_grade_1_2"],
            },
            {
                "testId": "t04",
                "question": "3학년 소인수 과목은 몇 명 이하일 때 석차등급 대신 점 표기가 가능한가요?",
                "expectedTopicIds": ["subject_progress_grade_3"],
                "expectedPolicyId": "grade_difference",
                "mustMention": ["3학년", "13명 이하", "같은 과목에는 동일 방식 적용"],
                "shouldUseCards": ["qa_subject_small_class_rank_rule", "rule_small_class_rank_marker_by_grade"],
            },
            {
                "testId": "t05",
                "question": "한자로 세특을 적어도 되나요?",
                "expectedTopicIds": ["processing"],
                "expectedPolicyId": "recordability",
                "mustMention": ["한글이 원칙", "부득이한 경우 영문만 가능", "한자 입력 불가"],
                "shouldUseCards": ["rule_hangul_default_english_only", "qa_processing_hanja_input"],
            },
            {
                "testId": "t06",
                "question": "학교교육계획에 없던 교내상도 학생부 수상경력에 넣을 수 있나요?",
                "expectedTopicIds": ["awards"],
                "expectedPolicyId": "recordability",
                "mustMention": ["학교교육계획 반영 여부 확인", "2학기 초 30일 이내 변경계획 공개 여부 확인"],
                "shouldUseCards": ["chg_2026_007_award_plan", "rule_awards_must_follow_school_plan"],
            },
            {
                "testId": "t07",
                "question": "물품 기부를 봉사시간으로 바꿔 적을 수 있나요?",
                "expectedTopicIds": ["volunteer_service"],
                "expectedPolicyId": "recordability",
                "mustMention": ["단순 기부는 봉사활동으로 인정하지 않음"],
                "shouldUseCards": ["rule_volunteer_no_simple_donation", "qa_volunteer_simple_donation"],
            },
            {
                "testId": "t08",
                "question": "참고인 조사 출석 때문에 빠진 날은 미인정결석인가요?",
                "expectedTopicIds": ["attendance"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["학교가 출석인정 결석 또는 기타결석으로 판단 가능", "자동으로 미인정결석이라고 단정하지 않음"],
                "shouldUseCards": ["qa_attendance_reference_witness_and_juvenile_case"],
            },
            {
                "testId": "t09",
                "question": "같은 책을 여러 과목에서 읽으면 독서활동상황에 한 번만 적어야 하나요?",
                "expectedTopicIds": ["reading"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["증빙자료가 다르면 중복 입력 가능"],
                "shouldUseCards": ["chg_2026_027_reading_duplication", "qa_reading_same_book_duplication"],
            },
            {
                "testId": "t10",
                "question": "예전 학년 세특이 학생끼리 뒤바뀐 경우 정정할 수 있나요?",
                "expectedTopicIds": ["corrections"],
                "expectedPolicyId": "recordability",
                "mustMention": ["객관적 증빙자료", "학업성적관리위원회 심의", "입력 주체 과실 확인"],
                "shouldUseCards": ["rule_correction_swapped_items_committee", "qa_correction_swapped_descriptive_items"],
            },
            {
                "testId": "t11",
                "question": "2026학년도 과목출석률 기준은 어떻게 설명해야 하나요?",
                "expectedTopicIds": ["attendance", "subject_progress_grades_1_2"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["1학점당 수업량 16회의 3분의 2 이상", "1·2학년 기준", "출석인정 결석 또는 결과는 출석 반영"],
                "shouldUseCards": ["chg_2026_004_subject_attendance_rate", "rule_subject_attendance_rate_16_sessions", "qa_subject_attendance_recognized_absence"],
            },
            {
                "testId": "t12",
                "question": "봉사활동 입력 방법 원문 페이지를 알려 주세요.",
                "expectedTopicIds": ["volunteer_service"],
                "expectedPolicyId": "page_lookup",
                "mustMention": ["공식 기재요령", "인쇄 쪽수", "PDF 화면상 페이지", "길라잡이 Q&A 페이지"],
                "shouldUseCards": [],
            },
            {
                "testId": "t13",
                "question": "창체나 행특 누가기록은 교육청 기준으로 똑같이 운영되나요?",
                "expectedTopicIds": ["creative_experience", "behavior"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["학교장이 정함", "학교별 방침 확인", "전국 공통으로 단정하면 안 됨"],
                "shouldUseCards": ["chg_2026_001_accumulation_authority", "rule_accumulation_decided_by_principal", "qa_accumulation_principal_policy"],
            },
            {
                "testId": "t14",
                "question": "졸업에 필요한 학점을 못 채우면 유급인가요?",
                "expectedTopicIds": ["personal_school_status"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["유급과 졸업유예 구분", "진급 문제와 졸업 자격 문제 구분"],
                "shouldUseCards": ["chg_2026_002_retention_definition", "chg_2026_003_graduation_deferral", "qa_retention_vs_graduation_deferral"],
            },
            {
                "testId": "t15",
                "question": "수행평가에서 생성형 AI 사용을 허용해도 되나요?",
                "expectedTopicIds": ["subject_progress"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["사전 안내", "공정성과 신뢰도", "교사 직접 관찰"],
                "shouldUseCards": ["chg_2026_025_performance_assessment_ai", "rule_performance_assessment_ai_caution", "qa_performance_assessment_ai"],
            },
            {
                "testId": "t16",
                "question": "정규교육과정 이외 학교스포츠클럽은 시간과 특기사항도 적나요?",
                "expectedTopicIds": ["creative_experience"],
                "expectedPolicyId": "recordability",
                "mustMention": ["동아리명만 입력", "활동시간 미기재", "특기사항 미입력"],
                "shouldUseCards": ["chg_2026_013_school_sports_hours_removed", "chg_2026_014_school_sports_special_note_removed", "qa_school_sports_club_record"],
            },
        ],
    }


def build_test_questions_v3() -> dict:
    return {
        "schemaVersion": "2026-06-17.curated.v3",
        "tests": [
            {
                "testId": "t01",
                "question": "2026년 변경사항",
                "expectedTopicIds": ["processing", "attendance", "subject_progress"],
                "expectedPolicyId": "change_2026",
                "mustMention": [
                    "2026 변경사항은 공식 기재요령 기준으로 설명",
                    "학년별 차이가 있는 항목은 분기해서 설명",
                    "AI 관련 유의사항",
                    "누가기록 여부 및 방법은 학교장이 정함",
                    "유급과 졸업유예 구분",
                    "과목출석률",
                    "출결 특기사항 기준 세분화",
                    "글자 수 축소",
                    "창체 영역명 학년별 차이",
                    "교과학습발달상황 1·2학년과 3학년 분리",
                    "지필평가 → 정기시험",
                    "세특 모든 학생 입력 원칙",
                ],
                "shouldUseCards": [
                    "chg_2026_001_accumulation_authority",
                    "chg_2026_002_retention_definition",
                    "chg_2026_003_graduation_deferral",
                    "chg_2026_004_subject_attendance_rate",
                    "chg_2026_005_attendance_notes",
                    "chg_2026_009_generative_ai_caution",
                    "chg_2026_015_volunteer_content_limit",
                    "chg_2026_017_behavior_limit",
                    "chg_2026_018_subject_progress_split",
                    "chg_2026_023_regular_exam_term",
                    "chg_2026_026_all_students_subject_notes",
                ],
            },
            {
                "testId": "t02",
                "question": "2026년에 출결 특기사항 뭐가 바뀜?",
                "expectedTopicIds": ["attendance"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["장기결석", "기타결석 1일이라도 입력", "지각·조퇴·결과는 반복적일 때만 사유 입력 가능"],
                "shouldUseCards": ["chg_2026_005_attendance_notes", "rule_long_absence_special_note", "rule_tardy_earlyleave_result_note"],
            },
            {
                "testId": "t03",
                "question": "1,2학년이랑 3학년 생기부 차이",
                "expectedTopicIds": ["subject_progress", "creative_experience"],
                "expectedPolicyId": "grade_difference",
                "mustMention": ["1·2학년과 3학년 분리", "학점과 5등급", "단위수와 9등급", "창체 영역명 차이"],
                "shouldUseCards": ["chg_2026_018_subject_progress_split", "rule_grade_1_2_credit_5_grade", "rule_grade_3_unit_9_grade", "rule_creative_area_names_by_grade"],
            },
            {
                "testId": "t04",
                "question": "졸업에 필요한 학점을 못 채우면 유급인가요?",
                "expectedTopicIds": ["personal_school_status"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["유급과 졸업유예 구분", "진급 문제인지 졸업 자격 문제인지 구분"],
                "shouldUseCards": ["chg_2026_002_retention_definition", "chg_2026_003_graduation_deferral", "rule_retention_vs_graduation_deferral"],
            },
            {
                "testId": "t05",
                "question": "창체나 행특 누가기록은 교육청 기준으로 똑같이 운영되나요?",
                "expectedTopicIds": ["creative_experience", "behavior"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["학교장이 정함", "학교별 방침 확인", "전국 공통으로 단정하면 안 됨"],
                "shouldUseCards": ["chg_2026_001_accumulation_authority", "rule_accumulation_decided_by_principal", "qa_accumulation_principal_policy"],
            },
            {
                "testId": "t06",
                "question": "수행평가에서 생성형 AI 사용을 허용해도 되나요?",
                "expectedTopicIds": ["subject_progress"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["사전 안내", "공정성과 신뢰도", "교사 직접 관찰"],
                "shouldUseCards": ["chg_2026_025_performance_assessment_ai", "rule_performance_assessment_ai_caution", "qa_performance_assessment_ai"],
            },
            {
                "testId": "t07",
                "question": "정규교육과정 이외 학교스포츠클럽은 시간과 특기사항도 적나요?",
                "expectedTopicIds": ["creative_experience"],
                "expectedPolicyId": "recordability",
                "mustMention": ["동아리명만 입력", "활동시간 미기재", "특기사항 미입력"],
                "shouldUseCards": ["chg_2026_013_school_sports_hours_removed", "chg_2026_014_school_sports_special_note_removed", "rule_school_sports_club_name_only"],
            },
            {
                "testId": "t08",
                "question": "세특 문장 하나 써줘",
                "expectedTopicIds": ["processing", "subject_progress"],
                "expectedPolicyId": "recordability",
                "mustMention": ["교사가 직접 관찰한 사실 없이 대신 작성해 줄 수 없다고 안내", "작성 기준과 필요한 사실 정보를 먼저 확인"],
                "shouldUseCards": ["rule_teacher_owns_descriptive_items", "rule_subject_notes_for_all_students", "rule_no_direct_ai_generated_text"],
            },
            {
                "testId": "t09",
                "question": "학생이 써 온 세특 문장을 교사가 그대로 붙여 넣어도 되나요?",
                "expectedTopicIds": ["processing", "subject_progress"],
                "expectedPolicyId": "recordability",
                "mustMention": ["교사가 직접 작성해야 함", "학생 작성 문장을 그대로 입력하면 안 됨"],
                "shouldUseCards": ["rule_teacher_owns_descriptive_items", "rule_no_direct_ai_generated_text"],
            },
            {
                "testId": "t10",
                "question": "한자로 세특을 적어도 되나요?",
                "expectedTopicIds": ["processing"],
                "expectedPolicyId": "recordability",
                "mustMention": ["한글이 원칙", "부득이한 경우 영문만 가능", "한자 입력 불가"],
                "shouldUseCards": ["rule_hangul_default_english_only", "qa_processing_hanja_input"],
            },
            {
                "testId": "t11",
                "question": "학교교육계획에 없던 교내상도 학생부 수상경력에 넣을 수 있나요?",
                "expectedTopicIds": ["awards"],
                "expectedPolicyId": "recordability",
                "mustMention": ["학교교육계획 반영 여부 확인", "2학기 초 30일 이내 변경계획 공개 여부 확인"],
                "shouldUseCards": ["chg_2026_007_award_plan", "rule_awards_must_follow_school_plan", "qa_awards_competition_participation"],
            },
            {
                "testId": "t12",
                "question": "물품 기부를 봉사시간으로 바꿔 적을 수 있나요?",
                "expectedTopicIds": ["volunteer_service"],
                "expectedPolicyId": "recordability",
                "mustMention": ["단순 기부는 봉사활동으로 인정하지 않음"],
                "shouldUseCards": ["rule_volunteer_no_simple_donation", "qa_volunteer_simple_donation"],
            },
            {
                "testId": "t13",
                "question": "참고인 조사 출석 때문에 빠진 날은 미인정결석인가요?",
                "expectedTopicIds": ["attendance"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["학교가 출석인정 결석 또는 기타결석으로 판단 가능", "자동으로 미인정결석이라고 단정하지 않음"],
                "shouldUseCards": ["qa_attendance_reference_witness_and_juvenile_case"],
            },
            {
                "testId": "t14",
                "question": "같은 책을 여러 과목에서 읽으면 독서활동상황에 한 번만 적어야 하나요?",
                "expectedTopicIds": ["reading"],
                "expectedPolicyId": "qa_lookup",
                "mustMention": ["증빙자료가 다르면 중복 입력 가능"],
                "shouldUseCards": ["chg_2026_027_reading_duplication", "rule_reading_same_book_different_evidence", "qa_reading_same_book_duplication"],
            },
            {
                "testId": "t15",
                "question": "2026학년도 과목출석률 기준은 어떻게 설명해야 하나요?",
                "expectedTopicIds": ["attendance", "subject_progress_grades_1_2"],
                "expectedPolicyId": "change_2026",
                "mustMention": ["1학점당 수업량 16회의 3분의 2 이상", "1·2학년 기준", "출석인정 결석 또는 결과는 출석 반영"],
                "shouldUseCards": ["chg_2026_004_subject_attendance_rate", "rule_subject_attendance_rate_16_sessions", "qa_subject_attendance_recognized_absence"],
            },
            {
                "testId": "t16",
                "question": "예전 학년 세특이 학생끼리 뒤바뀐 경우 정정할 수 있나요?",
                "expectedTopicIds": ["corrections"],
                "expectedPolicyId": "recordability",
                "mustMention": ["객관적 증빙자료", "학업성적관리위원회 심의", "입력 주체 과실 확인"],
                "shouldUseCards": ["rule_correction_swapped_items_committee", "qa_correction_swapped_descriptive_items"],
            },
        ],
    }


def main() -> None:
    change_cards = enrich_change_cards(build_change_cards())
    rule_cards = enrich_rule_cards(build_rule_cards())
    qa_cards = build_qa_cards()
    test_questions = build_test_questions_v3()

    write_jsonl(BRAIN_DIR / "04_change_2026_catalog.jsonl", change_cards)
    write_jsonl(BRAIN_DIR / "05_rule_cards.jsonl", rule_cards)
    write_jsonl(BRAIN_DIR / "06_qa_cards.jsonl", qa_cards)
    write_json(BRAIN_DIR / "09_test_questions.json", test_questions)

    summary = {
        "changeCards": len(change_cards),
        "ruleCards": len(rule_cards),
        "qaCards": len(qa_cards),
        "testQuestions": len(test_questions["tests"]),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
